<?php

namespace CL\ContactBookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository {
// własne zapytanie dql używane w controlerze do sortowania contaktów
    public function findAllSort() {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                'SELECT c
                FROM CLContactBookBundle:Contact c
                ORDER BY c.name ASC');
        $contacts= $query->getResult();
        return $contacts;
    }

}
