<?php

namespace CL\ContactBookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends EntityRepository {
// my custom Dql query to sort contacts alphabetically
    public function findAllSort() {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                'SELECT c
                FROM CLContactBookBundle:Contact c
                ORDER BY c.name ASC');
        $contacts= $query->getResult();
        return $contacts;
    }
    public function findContactwithAddress($id){
        $em=$this->getEntityManager();
        $query= $em->createQuery(
                "SELECT c FROM CLContactBookBundle:Contact c WHERE c.id = $id"
                );
        return $query->getResult();
    }

}
