<?php

namespace CL\ContactBookBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TelephoneNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TelephoneNumberRepository extends EntityRepository
{
}
